// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: meowrpc/meow.proto

package meowrpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The request message containing the user's name.
type Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_meowrpc_meow_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_meowrpc_meow_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_meowrpc_meow_proto_rawDescGZIP(), []int{0}
}

func (x *Request) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// The response message containing the greetings
type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_meowrpc_meow_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_meowrpc_meow_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_meowrpc_meow_proto_rawDescGZIP(), []int{1}
}

func (x *Response) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_meowrpc_meow_proto protoreflect.FileDescriptor

const file_meowrpc_meow_proto_rawDesc = "" +
	"\n" +
	"\x12meowrpc/meow.proto\x12\ameowrpc\"#\n" +
	"\aRequest\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"$\n" +
	"\bResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2\xe6\x01\n" +
	"\aMeowRPC\x121\n" +
	"\bEchoMeow\x12\x10.meowrpc.Request\x1a\x11.meowrpc.Response\"\x00\x123\n" +
	"\bManyMeow\x12\x10.meowrpc.Request\x1a\x11.meowrpc.Response\"\x000\x01\x128\n" +
	"\rImpatientMeow\x12\x10.meowrpc.Request\x1a\x11.meowrpc.Response\"\x00(\x01\x129\n" +
	"\fConversation\x12\x10.meowrpc.Request\x1a\x11.meowrpc.Response\"\x00(\x010\x01B\x0eZ\fmeow/meowrpcb\x06proto3"

var (
	file_meowrpc_meow_proto_rawDescOnce sync.Once
	file_meowrpc_meow_proto_rawDescData []byte
)

func file_meowrpc_meow_proto_rawDescGZIP() []byte {
	file_meowrpc_meow_proto_rawDescOnce.Do(func() {
		file_meowrpc_meow_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_meowrpc_meow_proto_rawDesc), len(file_meowrpc_meow_proto_rawDesc)))
	})
	return file_meowrpc_meow_proto_rawDescData
}

var file_meowrpc_meow_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_meowrpc_meow_proto_goTypes = []any{
	(*Request)(nil),  // 0: meowrpc.Request
	(*Response)(nil), // 1: meowrpc.Response
}
var file_meowrpc_meow_proto_depIdxs = []int32{
	0, // 0: meowrpc.MeowRPC.EchoMeow:input_type -> meowrpc.Request
	0, // 1: meowrpc.MeowRPC.ManyMeow:input_type -> meowrpc.Request
	0, // 2: meowrpc.MeowRPC.ImpatientMeow:input_type -> meowrpc.Request
	0, // 3: meowrpc.MeowRPC.Conversation:input_type -> meowrpc.Request
	1, // 4: meowrpc.MeowRPC.EchoMeow:output_type -> meowrpc.Response
	1, // 5: meowrpc.MeowRPC.ManyMeow:output_type -> meowrpc.Response
	1, // 6: meowrpc.MeowRPC.ImpatientMeow:output_type -> meowrpc.Response
	1, // 7: meowrpc.MeowRPC.Conversation:output_type -> meowrpc.Response
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_meowrpc_meow_proto_init() }
func file_meowrpc_meow_proto_init() {
	if File_meowrpc_meow_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_meowrpc_meow_proto_rawDesc), len(file_meowrpc_meow_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_meowrpc_meow_proto_goTypes,
		DependencyIndexes: file_meowrpc_meow_proto_depIdxs,
		MessageInfos:      file_meowrpc_meow_proto_msgTypes,
	}.Build()
	File_meowrpc_meow_proto = out.File
	file_meowrpc_meow_proto_goTypes = nil
	file_meowrpc_meow_proto_depIdxs = nil
}
