// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: meowrpc/meow.proto

package meowrpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MeowRPC_EchoMeow_FullMethodName      = "/meowrpc.MeowRPC/EchoMeow"
	MeowRPC_ManyMeow_FullMethodName      = "/meowrpc.MeowRPC/ManyMeow"
	MeowRPC_ImpatientMeow_FullMethodName = "/meowrpc.MeowRPC/ImpatientMeow"
	MeowRPC_Conversation_FullMethodName  = "/meowrpc.MeowRPC/Conversation"
)

// MeowRPCClient is the client API for MeowRPC service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// A Cat live in RPC Server
type MeowRPCClient interface {
	// Echo Meow
	EchoMeow(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
	// Echo Many Meow Meow
	ManyMeow(ctx context.Context, in *Request, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Response], error)
	// Cat summarize your chi-chat and meow
	ImpatientMeow(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[Request, Response], error)
	// A clever cat talks to you rationally.
	Conversation(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[Request, Response], error)
}

type meowRPCClient struct {
	cc grpc.ClientConnInterface
}

func NewMeowRPCClient(cc grpc.ClientConnInterface) MeowRPCClient {
	return &meowRPCClient{cc}
}

func (c *meowRPCClient) EchoMeow(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, MeowRPC_EchoMeow_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *meowRPCClient) ManyMeow(ctx context.Context, in *Request, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Response], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &MeowRPC_ServiceDesc.Streams[0], MeowRPC_ManyMeow_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Request, Response]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MeowRPC_ManyMeowClient = grpc.ServerStreamingClient[Response]

func (c *meowRPCClient) ImpatientMeow(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[Request, Response], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &MeowRPC_ServiceDesc.Streams[1], MeowRPC_ImpatientMeow_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Request, Response]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MeowRPC_ImpatientMeowClient = grpc.ClientStreamingClient[Request, Response]

func (c *meowRPCClient) Conversation(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[Request, Response], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &MeowRPC_ServiceDesc.Streams[2], MeowRPC_Conversation_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Request, Response]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MeowRPC_ConversationClient = grpc.BidiStreamingClient[Request, Response]

// MeowRPCServer is the server API for MeowRPC service.
// All implementations must embed UnimplementedMeowRPCServer
// for forward compatibility.
//
// A Cat live in RPC Server
type MeowRPCServer interface {
	// Echo Meow
	EchoMeow(context.Context, *Request) (*Response, error)
	// Echo Many Meow Meow
	ManyMeow(*Request, grpc.ServerStreamingServer[Response]) error
	// Cat summarize your chi-chat and meow
	ImpatientMeow(grpc.ClientStreamingServer[Request, Response]) error
	// A clever cat talks to you rationally.
	Conversation(grpc.BidiStreamingServer[Request, Response]) error
	mustEmbedUnimplementedMeowRPCServer()
}

// UnimplementedMeowRPCServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMeowRPCServer struct{}

func (UnimplementedMeowRPCServer) EchoMeow(context.Context, *Request) (*Response, error) {
	return nil, status.Error(codes.Unimplemented, "method EchoMeow not implemented")
}
func (UnimplementedMeowRPCServer) ManyMeow(*Request, grpc.ServerStreamingServer[Response]) error {
	return status.Error(codes.Unimplemented, "method ManyMeow not implemented")
}
func (UnimplementedMeowRPCServer) ImpatientMeow(grpc.ClientStreamingServer[Request, Response]) error {
	return status.Error(codes.Unimplemented, "method ImpatientMeow not implemented")
}
func (UnimplementedMeowRPCServer) Conversation(grpc.BidiStreamingServer[Request, Response]) error {
	return status.Error(codes.Unimplemented, "method Conversation not implemented")
}
func (UnimplementedMeowRPCServer) mustEmbedUnimplementedMeowRPCServer() {}
func (UnimplementedMeowRPCServer) testEmbeddedByValue()                 {}

// UnsafeMeowRPCServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MeowRPCServer will
// result in compilation errors.
type UnsafeMeowRPCServer interface {
	mustEmbedUnimplementedMeowRPCServer()
}

func RegisterMeowRPCServer(s grpc.ServiceRegistrar, srv MeowRPCServer) {
	// If the following call panics, it indicates UnimplementedMeowRPCServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MeowRPC_ServiceDesc, srv)
}

func _MeowRPC_EchoMeow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MeowRPCServer).EchoMeow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MeowRPC_EchoMeow_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MeowRPCServer).EchoMeow(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _MeowRPC_ManyMeow_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Request)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MeowRPCServer).ManyMeow(m, &grpc.GenericServerStream[Request, Response]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MeowRPC_ManyMeowServer = grpc.ServerStreamingServer[Response]

func _MeowRPC_ImpatientMeow_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(MeowRPCServer).ImpatientMeow(&grpc.GenericServerStream[Request, Response]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MeowRPC_ImpatientMeowServer = grpc.ClientStreamingServer[Request, Response]

func _MeowRPC_Conversation_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(MeowRPCServer).Conversation(&grpc.GenericServerStream[Request, Response]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MeowRPC_ConversationServer = grpc.BidiStreamingServer[Request, Response]

// MeowRPC_ServiceDesc is the grpc.ServiceDesc for MeowRPC service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MeowRPC_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "meowrpc.MeowRPC",
	HandlerType: (*MeowRPCServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "EchoMeow",
			Handler:    _MeowRPC_EchoMeow_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ManyMeow",
			Handler:       _MeowRPC_ManyMeow_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ImpatientMeow",
			Handler:       _MeowRPC_ImpatientMeow_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "Conversation",
			Handler:       _MeowRPC_Conversation_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "meowrpc/meow.proto",
}
